using Test

include("test_utilities.jl")

@testset "FFCM" begin
    include("test_cell_geometry.jl")
    include("test_wrap_positions.jl")
    include("test_assign_cells_kernel.jl")
    include("test_assign_cells.jl")
    include("test_assign_cells_api.jl")
    include("test_sort_particles_by_cell.jl")
    include("test_sort_particles_by_cell_api.jl")
    include("test_fcm_grid.jl")
    include("test_modified_kernel_coefficients.jl")
    include("test_spread_forces.jl")
    include("test_spread_forces_api.jl")
    include("test_stokes_solve.jl")
    include("test_stokes_solve_api.jl")
    include("test_interpolate_velocities.jl")
    include("test_interpolate_velocities_api.jl")
    include("test_correct_velocities.jl")
    include("test_correct_velocities_api.jl")
    include("test_mobility.jl")
    include("test_mobility_api.jl")
    include("test_mobility_properties.jl")
    include("test_single_sphere_mobility.jl")
    include("test_exported_surface.jl")
    include("test_aqua.jl")
    include("test_jet.jl")
end
